apiVersion: 1

datasources:
  - name: TravelHub PostgreSQL
    type: postgres
    url: db:5432
    database: travelhub
    user: travelhub
    secureJsonData:
      password: travelhub123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
